git-debimport gettext_0.19.2-1.debian.tar.xz

diff --git a/gettext-tools/tests/lang-clisp b/gettext-tools/tests/lang-clisp
--- a/gettext-tools/tests/lang-clisp
+++ b/gettext-tools/tests/lang-clisp
@@ -1,16 +1,13 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the CLISP language.
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: clisp.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.lisp"
 cat <<\EOF > prog.lisp
 (setf (textdomain) "prog")
-(setf (textdomaindir "prog") "./")
+(setf (textdomaindir "prog") "./l-clisp/")
 
 (setq n (parse-integer (first *args*)))
 
@@ -21,15 +18,11 @@ cat <<\EOF > prog.lisp
 (format t "~A~%" (format nil (gettext "~A is replaced by ~A.") "FF" "EUR"))
 EOF
 
-tmpfiles="$tmpfiles prog.tmp prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.tmp --omit-header --no-location prog.lisp
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < prog.tmp > prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${XGETTEXT} -o l-clisp-prog.tmp --omit-header --no-location prog.lisp || exit 1
+LC_ALL=C tr -d '\r' < l-clisp-prog.tmp > l-clisp-prog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
-cat <<EOF > prog.ok
+cat <<EOF > l-clisp-prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
 
@@ -45,10 +38,9 @@ msgstr ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} prog.ok prog.pot || exit 1
+${DIFF} l-clisp-prog.ok l-clisp-prog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
-cat <<\EOF > fr.po
+cat <<\EOF > l-clisp-fr.po
 msgid ""
 msgstr ""
 "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -70,45 +62,42 @@ msgid "~A is replaced by ~A."
 msgstr "~1@*~A remplace ~0@*~A."
 EOF
 
-tmpfiles="$tmpfiles fr.po.tmp fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o l-clisp-fr.po.tmp l-clisp-fr.po l-clisp-prog.pot || exit 1
+LC_ALL=C tr -d '\r' < l-clisp-fr.po.tmp > l-clisp-fr.po.new || exit 1
 
 : ${DIFF=diff}
-${DIFF} fr.po fr.po.new || exit 1
+${DIFF} l-clisp-fr.po l-clisp-fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
-test -d fr || mkdir fr
-test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
+test -d l-clisp || mkdir l-clisp
+test -d l-clisp/fr || mkdir l-clisp/fr
+test -d l-clisp/fr/LC_MESSAGES || mkdir l-clisp/fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
-${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
+${MSGFMT} -o l-clisp/fr/LC_MESSAGES/prog.mo l-clisp-fr.po
 
 # Test for presence of clisp version 2.28 or newer with gettext support.
 # Use clisp for the comparison of the version numbers; neither 'expr' nor 'bc'
 # can deal with floating-point numbers.
 (clisp --version) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: clisp not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: clisp not found"; exit 77; }
 version=`clisp --version | sed -n -e 1p | sed -e 's/^[^0-9]*//'`
 case $version in
   19* | 20*) # older than 2.25
-    echo "Skipping test: clisp version too old"; rm -fr $tmpfiles; exit 77;;
+    echo "Skipping test: clisp version too old"; exit 77;;
 esac
 version=`echo $version | sed -e 's/^\([0-9]*\.[0-9]*\).*/\1/'`
 clisp -norc -x "(sys::exit #+GETTEXT (not (>= $version 2.28)) #-GETTEXT t)" \
       >/dev/null \
   || { echo "Skipping test: clisp was built without gettext support"
-       rm -fr $tmpfiles; exit 77
+       exit 77
      }
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LC_ALL=$LOCALE_FR ./testlocale
+  LC_ALL=$LOCALE_FR ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
@@ -116,7 +105,7 @@ if test $LOCALE_FR != none; then
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LC_ALL=$LOCALE_FR_UTF8 ./testlocale
+  LC_ALL=$LOCALE_FR_UTF8 ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
@@ -129,17 +118,16 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  rm -fr $tmpfiles; exit 77
+  exit 77
 fi
 
-tmpfiles="$tmpfiles prog.ok prog.oku prog.out"
 : ${DIFF=diff}
-cat <<\EOF > prog.ok
+cat <<\EOF > l-clisp-prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
 2 morceaux de gateau
 EUR remplace FF.
 EOF
-cat <<\EOF > prog.oku
+cat <<\EOF > l-clisp-prog.oku
 Â«Votre commande, s'il vous plaitÂ», dit le garÃ§on.
 2 morceaux de gateau
 EUR remplace FF.
@@ -148,16 +136,14 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR clisp prog.lisp 2 > prog.tmp || exit 1
-  LC_ALL=C tr -d '\r' < prog.tmp > prog.out || exit 1
-  ${DIFF} prog.ok prog.out || exit 1
+  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR clisp prog.lisp 2 > l-clisp-prog.tmp || exit 1
+  LC_ALL=C tr -d '\r' < l-clisp-prog.tmp > l-clisp-prog.out || exit 1
+  ${DIFF} l-clisp-prog.ok l-clisp-prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 clisp prog.lisp 2 > prog.tmp || exit 1
-  LC_ALL=C tr -d '\r' < prog.tmp > prog.out || exit 1
-  ${DIFF} prog.oku prog.out || exit 1
+  CLISP_LANGUAGE= LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 clisp prog.lisp 2 > l-clisp-prog.tmp || exit 1
+  LC_ALL=C tr -d '\r' < l-clisp-prog.tmp > l-clisp-prog.out || exit 1
+  ${DIFF} l-clisp-prog.oku l-clisp-prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext-tools/tests/lang-gawk b/gettext-tools/tests/lang-gawk
--- a/gettext-tools/tests/lang-gawk
+++ b/gettext-tools/tests/lang-gawk
@@ -1,4 +1,5 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the GNU awk language.
 # Assumes an fr_FR locale is installed.
@@ -8,14 +9,10 @@
 # but not in the fr_FR.UTF-8 locale. Probably because in the fr_FR locale,
 # nl_langinfo(CODESET) returns "".
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.awk"
 cat <<\EOF > prog.awk
 BEGIN {
   TEXTDOMAIN = "prog"
-  bindtextdomain ("./")
+  bindtextdomain ("./l-gawk")
 
   print _"'Your command, please?', asked the waiter."
 
@@ -25,15 +22,11 @@ BEGIN {
 }
 EOF
 
-tmpfiles="$tmpfiles prog.tmp prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.tmp --omit-header --no-location prog.awk
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < prog.tmp > prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${XGETTEXT} -o l-gawk-prog.tmp --omit-header --no-location prog.awk || exit 1
+LC_ALL=C tr -d '\r' < l-gawk-prog.tmp > l-gawk-prog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
-cat <<EOF > prog.ok
+cat <<EOF > l-gawk-prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
 
@@ -49,10 +42,9 @@ msgstr ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} prog.ok prog.pot || exit 1
+${DIFF} l-gawk-prog.ok l-gawk-prog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
-cat <<\EOF > fr.po
+cat <<\EOF > l-gawk-fr.po
 msgid ""
 msgstr ""
 "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -74,36 +66,33 @@ msgid "%s is replaced by %s."
 msgstr "%2$s remplace %1$s."
 EOF
 
-tmpfiles="$tmpfiles fr.po.tmp fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o l-gawk-fr.po.tmp l-gawk-fr.po l-gawk-prog.pot || exit 1
+LC_ALL=C tr -d '\r' < l-gawk-fr.po.tmp > l-gawk-fr.po.new || exit 1
 
 : ${DIFF=diff}
-${DIFF} fr.po fr.po.new || exit 1
+${DIFF} l-gawk-fr.po l-gawk-fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
-test -d fr || mkdir fr
-test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
+test -d l-gawk || mkdir l-gawk
+test -d l-gawk/fr || mkdir l-gawk/fr
+test -d l-gawk/fr/LC_MESSAGES || mkdir l-gawk/fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
-${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
+${MSGFMT} -o l-gawk/fr/LC_MESSAGES/prog.mo l-gawk-fr.po
 
 # Test for presence of gawk version 3.1.3 or newer, excluding version 3.1.5.
 (gawk --version) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: gawk not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: gawk not found"; exit 77; }
 case `gawk --version 2>&1 | sed -e 's/^[^0-9]*//'` in
   0.* | 1.* | 2.* | 3.0* | 3.1.0* | 3.1.1* | 3.1.2* | 3.1.5*)
-    echo "Skipping test: gawk version too old"; rm -fr $tmpfiles; exit 77;;
+    echo "Skipping test: gawk version too old"; exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LC_ALL=$LOCALE_FR ./testlocale
+  LC_ALL=$LOCALE_FR ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
@@ -111,7 +100,7 @@ if test $LOCALE_FR != none; then
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LC_ALL=$LOCALE_FR_UTF8 ./testlocale
+  LC_ALL=$LOCALE_FR_UTF8 ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
@@ -124,7 +113,7 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  rm -fr $tmpfiles; exit 77
+  exit 77
 fi
 
 # Test that gawk wasn't built with --disable-nls.
@@ -134,25 +123,24 @@ if test $LOCALE_FR != none; then
   LANGUAGE= LC_ALL=$LOCALE_FR gawk --version | grep logiciel > /dev/null
   test $? = 0 || {
     echo "Skipping test: gawk was built without i18n support"
-    rm -fr $tmpfiles; exit 77
+    exit 77
   }
 fi
 if test $LOCALE_FR_UTF8 != none; then
   LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 gawk --version | grep logiciel > /dev/null
   test $? = 0 || {
     echo "Skipping test: gawk was built without i18n support"
-    rm -fr $tmpfiles; exit 77
+    exit 77
   }
 fi
 
-tmpfiles="$tmpfiles prog.ok prog.oku prog.out"
 : ${DIFF=diff}
-cat <<\EOF > prog.ok
+cat <<\EOF > l-gawk-prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
 2 morceaux de gateau
 EUR remplace FF.
 EOF
-cat <<\EOF > prog.oku
+cat <<\EOF > l-gawk-prog.oku
 Â«Votre commande, s'il vous plaitÂ», dit le garÃ§on.
 2 morceaux de gateau
 EUR remplace FF.
@@ -161,14 +149,12 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR gawk -v n=2 -f prog.awk > prog.out || exit 1
-  ${DIFF} prog.ok prog.out || exit 1
+  LANGUAGE= LC_ALL=$LOCALE_FR gawk -v n=2 -f prog.awk > l-gawk-prog.out || exit 1
+  ${DIFF} l-gawk-prog.ok l-gawk-prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 gawk -v n=2 -f prog.awk > prog.out || exit 1
-  ${DIFF} prog.oku prog.out || exit 1
+  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 gawk -v n=2 -f prog.awk > l-gawk-prog.out || exit 1
+  ${DIFF} l-gawk-prog.oku l-gawk-prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
