git-debimport gettext_0.19.2.orig.tar.xz

diff --git a/gettext-tools/tests/lang-bash b/gettext-tools/tests/lang-bash
--- a/gettext-tools/tests/lang-bash
+++ b/gettext-tools/tests/lang-bash
@@ -1,4 +1,5 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src ${top_srcdir=..}/../gettext-runtime/src
 
 # Test of gettext facilities in the bash language.
 # Assumes an fr_FR locale is installed.
@@ -9,11 +10,7 @@
 # output when accessing any .mo file not generated from a .po file in UTF-8
 # encoding.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.sh"
-cat <<\EOF > prog.sh
+cat <<\EOF > prog.bash
 #! /bin/bash
 
 n=$1
@@ -22,7 +19,7 @@ n=$1
 
 TEXTDOMAIN=prog
 export TEXTDOMAIN
-TEXTDOMAINDIR=.
+TEXTDOMAINDIR=l-bash
 export TEXTDOMAINDIR
 
 $echo $"'Your command, please?', asked the waiter."
@@ -30,19 +27,16 @@ $echo $"'Your command, please?', asked the waiter."
 $echo "`eval_ngettext "a piece of cake" "\\$n pieces of cake" $n`"
 EOF
 
-tmpfiles="$tmpfiles prog.tmp prog.pot prog.err"
 : ${XGETTEXT=xgettext}
 LC_MESSAGES=C LC_ALL= \
-${XGETTEXT} -o prog.tmp --omit-header --no-location prog.sh \
-  >prog.err 2>&1
+${XGETTEXT} -o l-bash-prog.tmp --omit-header --no-location prog.bash \
+  >l-bash-prog.err 2>&1
 result=$?
-cat prog.err | grep -v 'warning: the syntax \$"\.\.\." is deprecated due to security reasons'
-test $result = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < prog.tmp > prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+cat l-bash-prog.err | grep -v 'warning: the syntax \$"\.\.\." is deprecated due to security reasons'
+test $result = 0 || { exit 1; }
+LC_ALL=C tr -d '\r' < l-bash-prog.tmp > l-bash-prog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
-cat <<\EOF > prog.ok
+cat <<\EOF > l-bash-prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
 
@@ -54,10 +48,9 @@ msgstr[1] ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} prog.ok prog.pot || exit 1
+${DIFF} l-bash-prog.ok l-bash-prog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
-cat <<\EOF > fr.po
+cat <<\EOF > l-bash-fr.po
 msgid ""
 msgstr ""
 "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -74,36 +67,33 @@ msgstr[0] "un morceau de gateau"
 msgstr[1] "$n morceaux de gateau"
 EOF
 
-tmpfiles="$tmpfiles fr.po.tmp fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o l-bash-fr.po.tmp l-bash-fr.po l-bash-prog.pot || exit 1
+LC_ALL=C tr -d '\r' < l-bash-fr.po.tmp > l-bash-fr.po.new || exit 1
 
 : ${DIFF=diff}
-${DIFF} fr.po fr.po.new || exit 1
+${DIFF} l-bash-fr.po l-bash-fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
-test -d fr || mkdir fr
-test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
+test -d l-bash || mkdir l-bash
+test -d l-bash/fr || mkdir l-bash/fr
+test -d l-bash/fr/LC_MESSAGES || mkdir l-bash/fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
-${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
+${MSGFMT} -o l-bash/fr/LC_MESSAGES/prog.mo l-bash-fr.po
 
 # Test for presence of bash version 2.0 or newer.
 (bash -c :) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: bash not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: bash not found"; exit 77; }
 case `bash -c 'echo $BASH_VERSION'` in
   [2-9].*) ;;
-  *) echo "Skipping test: bash version too old"; rm -fr $tmpfiles; exit 77;;
+  *) echo "Skipping test: bash version too old"; exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LC_ALL=$LOCALE_FR ./testlocale
+  LC_ALL=$LOCALE_FR ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
@@ -111,7 +101,7 @@ if test $LOCALE_FR != none; then
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LC_ALL=$LOCALE_FR_UTF8 ./testlocale
+  LC_ALL=$LOCALE_FR_UTF8 ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
@@ -124,21 +114,20 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  rm -fr $tmpfiles; exit 77
+  exit 77
 fi
 
-tmpfiles="$tmpfiles prog.nok prog.ok prog.oku prog.out"
 # Expected result when bash is built without i18n support.
-cat <<\EOF > prog.nok
+cat <<\EOF > l-bash-prog.nok
 'Your command, please?', asked the waiter.
 2 morceaux de gateau
 EOF
 # Expected result when bash is built with i18n support.
-cat <<\EOF > prog.ok
+cat <<\EOF > l-bash-prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
 2 morceaux de gateau
 EOF
-cat <<\EOF > prog.oku
+cat <<\EOF > l-bash-prog.oku
 Â«Votre commande, s'il vous plaitÂ», dit le garÃ§on.
 2 morceaux de gateau
 EOF
@@ -146,24 +135,22 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR bash ./prog.sh 2 > prog.out || exit 1
+  LANGUAGE= LC_ALL=$LOCALE_FR bash ./prog.bash 2 > l-bash-prog.out || exit 1
   : ${DIFF=diff}
-  ${DIFF} prog.nok prog.out > /dev/null && {
+  ${DIFF} l-bash-prog.nok l-bash-prog.out > /dev/null && {
     echo "Skipping test: bash is built without i18n support"
-    rm -fr $tmpfiles; exit 77
+    exit 77
   }
-  ${DIFF} prog.ok prog.out || exit 1
+  ${DIFF} l-bash-prog.ok l-bash-prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 bash ./prog.sh 2 > prog.out || exit 1
+  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 bash ./prog.bash 2 > l-bash-prog.out || exit 1
   : ${DIFF=diff}
-  ${DIFF} prog.nok prog.out > /dev/null && {
+  ${DIFF} l-bash-prog.nok l-bash-prog.out > /dev/null && {
     echo "Skipping test: bash is built without i18n support"
-    rm -fr $tmpfiles; exit 77
+    exit 77
   }
-  ${DIFF} prog.oku prog.out || exit 1
+  ${DIFF} l-bash-prog.oku l-bash-prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
diff --git a/gettext-tools/tests/lang-librep b/gettext-tools/tests/lang-librep
--- a/gettext-tools/tests/lang-librep
+++ b/gettext-tools/tests/lang-librep
@@ -1,18 +1,15 @@
 #! /bin/sh
+. "${srcdir=.}/init.sh"; path_prepend_ . ../src
 
 # Test of gettext facilities in the librep language.
 # Assumes an fr_FR locale is installed.
 # Assumes the following packages are installed: librep.
 
-tmpfiles=""
-trap 'rm -fr $tmpfiles' 1 2 3 15
-
-tmpfiles="$tmpfiles prog.jl"
 cat <<\EOF > prog.jl
 (require 'rep.i18n.gettext)
 
 (textdomain "prog")
-(bindtextdomain "prog" ".")
+(bindtextdomain "prog" "l-librep")
 
 (format standard-output "%s\n" (_ "'Your command, please?', asked the waiter."))
 
@@ -20,15 +17,11 @@ cat <<\EOF > prog.jl
         (format nil (_ "%s is replaced by %s.") "FF" "EUR"))
 EOF
 
-tmpfiles="$tmpfiles prog.tmp prog.pot"
 : ${XGETTEXT=xgettext}
-${XGETTEXT} -o prog.tmp --omit-header --no-location prog.jl
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < prog.tmp > prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${XGETTEXT} -o l-librep-prog.tmp --omit-header --no-location prog.jl || exit 1
+LC_ALL=C tr -d '\r' < l-librep-prog.tmp > l-librep-prog.pot || exit 1
 
-tmpfiles="$tmpfiles prog.ok"
-cat <<EOF > prog.ok
+cat <<EOF > l-librep-prog.ok
 msgid "'Your command, please?', asked the waiter."
 msgstr ""
 
@@ -38,10 +31,9 @@ msgstr ""
 EOF
 
 : ${DIFF=diff}
-${DIFF} prog.ok prog.pot || exit 1
+${DIFF} l-librep-prog.ok l-librep-prog.pot || exit 1
 
-tmpfiles="$tmpfiles fr.po"
-cat <<\EOF > fr.po
+cat <<\EOF > l-librep-fr.po
 msgid ""
 msgstr ""
 "Content-Type: text/plain; charset=ISO-8859-1\n"
@@ -56,36 +48,33 @@ msgid "%s is replaced by %s."
 msgstr "%2$s remplace %1$s."
 EOF
 
-tmpfiles="$tmpfiles fr.po.tmp fr.po.new"
 : ${MSGMERGE=msgmerge}
-${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new
-test $? = 0 || { rm -fr $tmpfiles; exit 1; }
+${MSGMERGE} -q -o l-librep-fr.po.tmp l-librep-fr.po l-librep-prog.pot || exit 1
+LC_ALL=C tr -d '\r' < l-librep-fr.po.tmp > l-librep-fr.po.new || exit 1
 
 : ${DIFF=diff}
-${DIFF} fr.po fr.po.new || exit 1
+${DIFF} l-librep-fr.po l-librep-fr.po.new || exit 1
 
-tmpfiles="$tmpfiles fr"
-test -d fr || mkdir fr
-test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
+test -d l-librep || mkdir l-librep
+test -d l-librep/fr || mkdir l-librep/fr
+test -d l-librep/fr/LC_MESSAGES || mkdir l-librep/fr/LC_MESSAGES
 
 : ${MSGFMT=msgfmt}
-${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
+${MSGFMT} -o l-librep/fr/LC_MESSAGES/prog.mo l-librep-fr.po
 
 # Test for presence of rep version 0.15.3 or newer.
 (rep --version) >/dev/null 2>/dev/null \
-  || { echo "Skipping test: rep not found"; rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: rep not found"; exit 77; }
 case `rep --version | sed -e 's/^[^0-9]*//'` in
   0.[0-9] | 0.1[0-5] | 0.[0-9].* | 0.1[0-4].* | 0.15.[0-2] )
-    echo "Skipping test: rep version too old"; rm -fr $tmpfiles; exit 77;;
+    echo "Skipping test: rep version too old"; exit 77;;
 esac
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LC_ALL=$LOCALE_FR ./testlocale
+  LC_ALL=$LOCALE_FR ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR=none;;
@@ -93,7 +82,7 @@ if test $LOCALE_FR != none; then
   esac
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LC_ALL=$LOCALE_FR_UTF8 ./testlocale
+  LC_ALL=$LOCALE_FR_UTF8 ../testlocale
   case $? in
     0) ;;
     77) LOCALE_FR_UTF8=none;;
@@ -106,16 +95,15 @@ if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
   else
     echo "Skipping test: no french locale is supported"
   fi
-  rm -fr $tmpfiles; exit 77
+  exit 77
 fi
 
-tmpfiles="$tmpfiles prog.ok prog.oku prog.out"
 : ${DIFF=diff}
-cat <<\EOF > prog.ok
+cat <<\EOF > l-librep-prog.ok
 «Votre commande, s'il vous plait», dit le garçon.
 EUR remplace FF.
 EOF
-cat <<\EOF > prog.oku
+cat <<\EOF > l-librep-prog.oku
 Â«Votre commande, s'il vous plaitÂ», dit le garÃ§on.
 EUR remplace FF.
 EOF
@@ -123,14 +111,12 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR rep --no-rc --batch prog.jl > prog.out || exit 1
-  ${DIFF} prog.ok prog.out || exit 1
+  LANGUAGE= LC_ALL=$LOCALE_FR rep --no-rc --batch prog.jl > l-librep-prog.out || exit 1
+  ${DIFF} l-librep-prog.ok l-librep-prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 rep --no-rc --batch prog.jl > prog.out || exit 1
-  ${DIFF} prog.oku prog.out || exit 1
+  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 rep --no-rc --batch prog.jl > l-librep-prog.out || exit 1
+  ${DIFF} l-librep-prog.oku l-librep-prog.out || exit 1
 fi
-
-rm -fr $tmpfiles
 
 exit 0
